dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  jwt_decoder: ^2.0.1
  qr_flutter: ^4.0.0
  intl: ^0.17.0
  cached_network_image: ^3.2.3
  flutter_secure_storage: ^8.0.0
  dio: ^5.0.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10